/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Read Me */
        get: operations["read_me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/organizations/{org_id}/members": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Org Members */
        get: operations["list_org_members_api_v1_organizations__org_id__members_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Farms */
        get: operations["list_farms_api_v1_farms_get"];
        put?: never;
        /** Post Farm */
        post: operations["post_farm_api_v1_farms_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/farms/{farm_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Farm */
        patch: operations["patch_farm_api_v1_farms__farm_id__patch"];
        trace?: never;
    };
    "/api/v1/farms/{farm_id}/plots": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List Plots */
        get: operations["list_plots_api_v1_farms__farm_id__plots_get"];
        put?: never;
        /** Post Plot */
        post: operations["post_plot_api_v1_farms__farm_id__plots_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plots/{plot_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Plot */
        patch: operations["patch_plot_api_v1_plots__plot_id__patch"];
        trace?: never;
    };
    "/api/v1/plots/{plot_id}/soil": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Put Soil */
        put: operations["put_soil_api_v1_plots__plot_id__soil_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plots/{plot_id}/soil:autofill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Autofill Soil
         * @description RF-03: autocomplete the soil profile from SoilGrids at the plot's
         *     centroid (T5). A full-document replace, same as `PUT .../soil`.
         */
        post: operations["autofill_soil_api_v1_plots__plot_id__soil_autofill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/crops": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * List Crops
         * @description Global crop catalog (docs/03-modelo-datos.md:115-127; docs/04-api.md:53):
         *     no org scoping, any authenticated user reads it.
         */
        get: operations["list_crops_api_v1_crops_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/plots/{plot_id}/cycles": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Cycle
         * @description docs/04-api.md:56; docs/00-glosario.md: at most one active cycle per
         *     plot. `expected_harvest_on` isn't in the request body: it's derived
         *     from the crop's FAO-56 stage lengths (T6 decision, `compute_expected_harvest_on`).
         */
        post: operations["post_cycle_api_v1_plots__plot_id__cycles_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/cycles/{cycle_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Patch Cycle */
        patch: operations["patch_cycle_api_v1_cycles__cycle_id__patch"];
        trace?: never;
    };
    "/api/v1/dev/auth/otp": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Request Otp */
        post: operations["request_otp_api_v1_dev_auth_otp_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/dev/auth/otp/verify": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Verify Otp */
        post: operations["verify_otp_api_v1_dev_auth_otp_verify_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** CropCycleCreateRequest */
        CropCycleCreateRequest: {
            /** Crop Id */
            crop_id: number;
            /**
             * Sown On
             * Format: date
             */
            sown_on: string;
        };
        /** CropCyclePatchRequest */
        CropCyclePatchRequest: {
            status?: components["schemas"]["CropCycleStatus"] | null;
            /** Expected Harvest On */
            expected_harvest_on?: string | null;
        };
        /**
         * CropCycleStatus
         * @enum {string}
         */
        CropCycleStatus: "active" | "harvested" | "lost";
        /** CropCycleView */
        CropCycleView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Plot Id
             * Format: uuid
             */
            plot_id: string;
            /** Crop Id */
            crop_id: number;
            /**
             * Sown On
             * Format: date
             */
            sown_on: string;
            /** Expected Harvest On */
            expected_harvest_on: string | null;
            status: components["schemas"]["CropCycleStatus"];
        };
        /** CropStageView */
        CropStageView: {
            /** Stage */
            stage: string;
            /** Length Days */
            length_days: number;
            /** Kc */
            kc: number;
            /** Depletion Fraction P */
            depletion_fraction_p: number;
        };
        /** CropView */
        CropView: {
            /** Id */
            id: number;
            /** Code */
            code: string;
            /** Name Es */
            name_es: string;
            /** Kc Source */
            kc_source: string;
            /** Stages */
            stages: components["schemas"]["CropStageView"][];
        };
        /** FarmCreateRequest */
        FarmCreateRequest: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Name */
            name: string;
            /** Municipality Code */
            municipality_code: string;
            location: components["schemas"]["GeoJSONPoint"];
            /** Technician Id */
            technician_id?: string | null;
        };
        /** FarmPage */
        FarmPage: {
            /** Items */
            items: components["schemas"]["FarmView"][];
            /** Next Cursor */
            next_cursor: string | null;
        };
        /** FarmPatchRequest */
        FarmPatchRequest: {
            /** Name */
            name?: string | null;
            /** Technician Id */
            technician_id?: string | null;
        };
        /** FarmView */
        FarmView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Name */
            name: string;
            /** Municipality Code */
            municipality_code: string;
            location: components["schemas"]["GeoJSONPoint"];
            /** Technician Id */
            technician_id: string | null;
        };
        /** GeoJSONPoint */
        GeoJSONPoint: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: [
                number,
                number
            ];
        };
        /** GeoJSONPolygon */
        GeoJSONPolygon: {
            /** Type */
            type: string;
            /** Coordinates */
            coordinates: [
                number,
                number
            ][][];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /**
         * IrrigationSystem
         * @enum {string}
         */
        IrrigationSystem: "none" | "drip" | "sprinkler" | "gravity";
        /** MeResponse */
        MeResponse: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string | null;
            /** Full Name */
            full_name: string | null;
            /** Memberships */
            memberships: components["schemas"]["MembershipView"][];
        };
        /** MemberView */
        MemberView: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * User Id
             * Format: uuid
             */
            user_id: string;
            /** Role */
            role: string;
        };
        /** MembershipView */
        MembershipView: {
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /** Role */
            role: string;
        };
        /** OtpRequest */
        OtpRequest: {
            /** Phone */
            phone: string;
        };
        /** OtpVerifyRequest */
        OtpVerifyRequest: {
            /** Phone */
            phone: string;
            /** Code */
            code: string;
        };
        /** PlotCreateRequest */
        PlotCreateRequest: {
            /** Name */
            name: string;
            boundary: components["schemas"]["GeoJSONPolygon"];
            irrigation_system: components["schemas"]["IrrigationSystem"];
            /** Irrigation Efficiency */
            irrigation_efficiency?: number | null;
            /** System Flow Lph */
            system_flow_lph?: number | null;
        };
        /** PlotPatchRequest */
        PlotPatchRequest: {
            /** Name */
            name?: string | null;
            boundary?: components["schemas"]["GeoJSONPolygon"] | null;
            irrigation_system?: components["schemas"]["IrrigationSystem"] | null;
            /** Irrigation Efficiency */
            irrigation_efficiency?: number | null;
            /** System Flow Lph */
            system_flow_lph?: number | null;
        };
        /** PlotView */
        PlotView: {
            /**
             * Id
             * Format: uuid
             */
            id: string;
            /**
             * Org Id
             * Format: uuid
             */
            org_id: string;
            /**
             * Farm Id
             * Format: uuid
             */
            farm_id: string;
            /** Name */
            name: string;
            boundary: components["schemas"]["GeoJSONPolygon"];
            /** Area Ha */
            area_ha: number;
            /** Weather Cell Id */
            weather_cell_id: number | null;
            irrigation_system: components["schemas"]["IrrigationSystem"];
            /** Irrigation Efficiency */
            irrigation_efficiency: number | null;
            /** System Flow Lph */
            system_flow_lph: number | null;
        };
        /** SoilProfilePutRequest */
        SoilProfilePutRequest: {
            /** Texture */
            texture?: string | null;
            /** Ph */
            ph?: number | null;
            /** Organic Matter Pct */
            organic_matter_pct?: number | null;
            /** Field Capacity Pct */
            field_capacity_pct?: number | null;
            /** Wilting Point Pct */
            wilting_point_pct?: number | null;
            /** Root Depth Cm */
            root_depth_cm?: number | null;
        };
        /** SoilProfileView */
        SoilProfileView: {
            /**
             * Plot Id
             * Format: uuid
             */
            plot_id: string;
            /** Source */
            source: string | null;
            /** Ph */
            ph: number | null;
            /** Organic Matter Pct */
            organic_matter_pct: number | null;
            /** Texture */
            texture: string | null;
            /** Field Capacity Pct */
            field_capacity_pct: number | null;
            /** Wilting Point Pct */
            wilting_point_pct: number | null;
            /** Root Depth Cm */
            root_depth_cm: number | null;
        };
        /** TokenResponse */
        TokenResponse: {
            /** Access Token */
            access_token: string;
            /**
             * Token Type
             * @default bearer
             */
            token_type: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    read_me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MeResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_org_members_api_v1_organizations__org_id__members_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                org_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_farms_api_v1_farms_get: {
        parameters: {
            query: {
                org_id: string;
                limit?: number;
                cursor?: string | null;
            };
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmPage"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_farm_api_v1_farms_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_farm_api_v1_farms__farm_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FarmPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FarmView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_plots_api_v1_farms__farm_id__plots_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlotView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_plot_api_v1_farms__farm_id__plots_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                farm_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlotCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_plot_api_v1_plots__plot_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["PlotPatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PlotView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_soil_api_v1_plots__plot_id__soil_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SoilProfilePutRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoilProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    autofill_soil_api_v1_plots__plot_id__soil_autofill_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plot_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SoilProfileView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    list_crops_api_v1_crops_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropView"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_cycle_api_v1_plots__plot_id__cycles_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                plot_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CropCycleCreateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropCycleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    patch_cycle_api_v1_cycles__cycle_id__patch: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                cycle_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CropCyclePatchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CropCycleView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    request_otp_api_v1_dev_auth_otp_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    verify_otp_api_v1_dev_auth_otp_verify_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OtpVerifyRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TokenResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
        };
    };
}
