"""Alerts domain package."""

from techcamp.alerts.domain.errors import (
    AlertNotFoundError,
    AlertRuleNotFoundError,
    InsufficientRoleError,
    InvalidAlertRuleError,
)
from techcamp.alerts.domain.models import (
    ESCALATION_DELAY,
    NON_PLOT_RULE_CODES,
    RESOLUTION_WINDOW,
    WATER_STRESS_UPGRADE_AFTER,
    Alert,
    AlertAction,
    AlertDecision,
    AlertRule,
    AlertRuleChanges,
    AlertState,
    InvalidAlertTransitionError,
    Severity,
    decide_alert,
    ensure_can_manage_alert,
    ensure_can_manage_rules,
    is_clear_met,
    is_condition_met,
    is_eligible_for_escalation,
    plot_rule_metric,
    resolve_threshold,
    sustained_run,
)

__all__ = [
    "ESCALATION_DELAY",
    "NON_PLOT_RULE_CODES",
    "RESOLUTION_WINDOW",
    "WATER_STRESS_UPGRADE_AFTER",
    "Alert",
    "AlertAction",
    "AlertDecision",
    "AlertNotFoundError",
    "AlertRule",
    "AlertRuleChanges",
    "AlertRuleNotFoundError",
    "AlertState",
    "InsufficientRoleError",
    "InvalidAlertRuleError",
    "InvalidAlertTransitionError",
    "Severity",
    "decide_alert",
    "ensure_can_manage_alert",
    "ensure_can_manage_rules",
    "is_clear_met",
    "is_condition_met",
    "is_eligible_for_escalation",
    "plot_rule_metric",
    "resolve_threshold",
    "sustained_run",
]
