"""Alerts domain package."""

from techcamp.alerts.domain.models import (
    ESCALATION_DELAY,
    RESOLUTION_WINDOW,
    WATER_STRESS_UPGRADE_AFTER,
    Alert,
    AlertAction,
    AlertDecision,
    AlertRule,
    AlertState,
    InvalidAlertTransitionError,
    Severity,
    decide_alert,
    is_clear_met,
    is_condition_met,
    is_eligible_for_escalation,
    is_escalation_eligible,
    resolve_threshold,
    sustained_run,
)

__all__ = [
    "Alert",
    "AlertAction",
    "AlertDecision",
    "AlertRule",
    "AlertState",
    "ESCALATION_DELAY",
    "InvalidAlertTransitionError",
    "RESOLUTION_WINDOW",
    "Severity",
    "WATER_STRESS_UPGRADE_AFTER",
    "decide_alert",
    "is_clear_met",
    "is_condition_met",
    "is_eligible_for_escalation",
    "is_escalation_eligible",
    "resolve_threshold",
    "sustained_run",
]
